// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: checkRevokeStatus.sql

package database

import (
	"context"
	"database/sql"
)

const checkRevokeStatus = `-- name: CheckRevokeStatus :one
SELECT revoked_at FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) CheckRevokeStatus(ctx context.Context, token string) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, checkRevokeStatus, token)
	var revoked_at sql.NullTime
	err := row.Scan(&revoked_at)
	return revoked_at, err
}
