// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: revokeRefresh.sql

package database

import (
	"context"
	"time"
)

const revokeRefresh = `-- name: RevokeRefresh :exec
UPDATE refresh_tokens
SET updated_at = $1, revoked_at = $1
WHERE token = $2 AND revoked_at IS NULL
`

type RevokeRefreshParams struct {
	UpdatedAt time.Time
	Token     string
}

func (q *Queries) RevokeRefresh(ctx context.Context, arg RevokeRefreshParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefresh, arg.UpdatedAt, arg.Token)
	return err
}
