// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: updateUserPass.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserPass = `-- name: UpdateUserPass :exec
UPDATE users
SET email = $2, hashed_password = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPassParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) UpdateUserPass(ctx context.Context, arg UpdateUserPassParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPass, arg.ID, arg.Email, arg.HashedPassword)
	return err
}
