// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: upgradeRed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeRed = `-- name: UpgradeRed :exec
UPDATE users
SET updated_at = NOW(), is_chirpy_red = true
WHERE id = $1
`

func (q *Queries) UpgradeRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgradeRed, id)
	return err
}
